package com.interview.school.courses.payload;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.interview.school.common.validation.CourseCode;
import lombok.Data;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;

/**
 * CourseDto.
 *
 * @author AbdulMuhsin J. Al-Kandari
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class CourseDto {
    private String courseId;

    @NotBlank
    private String courseName;
    /* Course Code as it would be defined by the school,
    whereas the course id is the id generated by the db.
     */
    @CourseCode
    private String courseCode;

    @Min(1)
    @Max(30)
    private int classSize;
}
